<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="L-INE-G6NSYZ2" failures="1" tests="3" name="com.Demowebshop.Runfile.RunnerClass$CucumberRunnerTests" time="48.067" errors="0" timestamp="2023-09-18T10:58:48 IST" skipped="0">
  <testcase classname="com.Demowebshop.Runfile.RunnerClass$CucumberRunnerTests" name="runScenario" time="16.505"/>
  <testcase classname="com.Demowebshop.Runfile.RunnerClass$CucumberRunnerTests" name="runScenario" time="10.661">
    <failure message="expected [Welcome to our store] but found [About login / registration]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Welcome to our store] but found [About login / registration]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.DemowebshopTest.StepDefinition.LoginStepDefinition.validate_with_login_successfull(LoginStepDefinition.java:37)
at âœ½.Validate with Login Successfull.(file:///C:/Users/mmaralinganavar/Desktop/Java_Fun_T/program/class_work/DemowebshopTest/src/test/resources/Features/Login.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.Demowebshop.Runfile.RunnerClass$CucumberRunnerTests" name="runScenario" time="20.901"/>
</testsuite> <!-- com.Demowebshop.Runfile.RunnerClass$CucumberRunnerTests -->
